services:
  frontend:
    build:
      context: ./src/client
      dockerfile: Dockerfile
    ports:
      - "3001:3000"  # React usa el puerto 3000 por defecto
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - app
    environment:
      - REACT_APP_API_URL=http://localhost:3001

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./.env
   
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4884
      POSTGRES_DB: ToDoList
    ports:
      - "5432:5432"